on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  find-subfolders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find subfolders to build
        id: find
        # List the two subdirectories under the src directory, trim src/ off the front of the path,
        # trim the final newline, and turn it into a json array for easier parsing in the next step.
        # Like: ["fabric-runtime/1.2","fabric-runtime/1.3"]
        run: |
          SUBFOLDERS=$(find src -mindepth 2 -maxdepth 2 -type d | sed 's|^src/||' | tr -d '\n' | jq --raw-input --slurp --compact-output 'split("\n")')
          echo "Found subfolders: $SUBFOLDERS"
          echo "SUBFOLDERS=$SUBFOLDERS" >> $GITHUB_ENV
    outputs:
      subfolders: ${{ env.SUBFOLDERS }}

  build:
    runs-on: ubuntu-latest
    needs: find-subfolders
    strategy:
      # Don't fail all the builds if one fails
      fail-fast: false
      matrix:
        subfolder: ${{ fromJson(needs.find-subfolders.outputs.subfolders) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse out the image name and tag
        id: parse
        run: |
          echo "Parsing subfolder: ${{ matrix.subfolder }}"

          # The first part is the image name
          IMAGE_NAME=$(echo ${{ matrix.subfolder }} | cut -d / -f 1)
          echo "The image name is: $IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

          # And the second part is the image tag
          IMAGE_TAG=$(echo ${{ matrix.subfolder }} | cut -d / -f 2)
          echo "The image tag is: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build images
        uses: devcontainers/ci@v0.3
        # Options: https://github.com/devcontainers/ci/blob/main/action.yml
        with:
          imageName: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
          cacheFrom: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
          imageTag: ${{ env.IMAGE_TAG }}
          push: always
          subFolder: src/${{ matrix.subfolder }}
